---
- name: Converge
  hosts: all
  tasks:
    - name: "Include iac_role_nginx"
      include_role:
        name: "iac_role_nginx"
      vars:
        nginx_extra_conf:
          - filename: test_file_1
            content: |
              upstream backend {
                 server backend1.example.com weight=5;
                 server backend2.example.com;
                 server 192.0.0.1 backup;
               }
          - filename: test_file_2
            content: |
              # Arquivo de teste
